### ISSUE TITLE
Set icon on notification

### ISSUE THREAD

**Issue by pzelnip** [knowsuchagency/klaxon#9]
Would be great if you could specify the icon on the notification.  Is there any way to do this that I'm just missing, or are you stuck with the default "pen & paper" icon?

**Comment by pzelnip** [comment]
Hrm, looks like it's not possible via osascript: https://stackoverflow.com/questions/48856158/change-icon-of-notification-when-using-osascript-e-display-notification

**Comment by knowsuchagency** [comment]
Yeah, I was hoping for a way to alter the icon as well, but you're right that it's limited by osascript. It might be possible to do more via `pyobjc`, however https://pyobjc.readthedocs.io/en/latest/apinotes/NotificationCenter.html
